FROM ubuntu:24.04

# Install dependencies
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update -qq && \
    apt-get install -y -qq --no-install-recommends \
      build-essential \
      ca-certificates \
      curl \
      expect \
      fuse \
      libfuse-dev \
      pkg-config \
      qemu-efi-riscv64 \
      qemu-system-riscv64 \
      rsync \
      nasm \
    && rm -rf /var/lib/apt/lists/*

# Install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
    sh -s -- --default-toolchain nightly --profile minimal -y

# Set path and target
ENV PATH=/root/.cargo/bin:$PATH
ENV TARGET=riscv64gc-unknown-redox

# Install redoxer
COPY . /root/redoxer
RUN cargo install --path /root/redoxer --locked

# Install redoxer toolchain
RUN redoxer toolchain

# TODO: RISC-V does not have a working driver for redoxer

# Ensure redoxer build is working
RUN cd /root/redoxer/example && redoxer build

# Strip unneeded files
RUN rm -rf /root/redoxer /root/.cargo/git /root/.cargo/registry 
